// Pair page: one model's responses on one theme, rendered at the edge from
// static shard assets. The HTML chrome comes from /data/pair-template.html
// (generated by preprocess.py), so this function never duplicates site markup.

const SHARD_FALLBACK = 8;

function fnv1a(s) {
  // Must match _fnv1a in preprocess.py.
  let h = 0x811c9dc5;
  const bytes = new TextEncoder().encode(s);
  for (const b of bytes) {
    h ^= b;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

async function fetchAsset(context, path) {
  const url = new URL(path, context.request.url);
  return context.env.ASSETS.fetch(url);
}

export async function onRequestGet(context) {
  const { theme, model } = context.params;
  if (!theme || !model) return new Response("Not found", { status: 404 });

  const metaResp = await fetchAsset(context, `/data/theme-shards/${theme}.meta.json`);
  if (!metaResp.ok) return new Response("Unknown theme", { status: 404 });
  const meta = await metaResp.json();

  const shardCount = meta.shards || SHARD_FALLBACK;
  const shard = fnv1a(model) % shardCount;
  const shardResp = await fetchAsset(context, `/data/theme-shards/${theme}.${shard}.json`);
  if (!shardResp.ok) return new Response("Missing data", { status: 404 });
  const entry = (await shardResp.json())[model];
  if (!entry) return new Response("Unknown model for this theme", { status: 404 });

  const tplResp = await fetchAsset(context, "/data/pair-template.html");
  if (!tplResp.ok) return new Response("Missing template", { status: 500 });
  const tpl = await tplResp.text();

  const themeName = meta.theme || theme;
  const title = `${entry.m} on ${themeName} — SpeechMap.AI`;
  const desc = `Full responses and judge analysis: how ${entry.m} handled the "${themeName}" prompts (${meta.domain}) on SpeechMap.AI.`;
  const canonical = `https://speechmap.ai/themes/${theme}/m/${model}/`;

  const html = tpl
    .replaceAll("__TITLE__", esc(title))
    .replaceAll("__DESC__", esc(desc))
    .replaceAll("__CANONICAL__", esc(canonical))
    .replaceAll("__MODEL__", esc(entry.m))
    .replaceAll("__MODEL_SAFE__", esc(model))
    .replaceAll("__THEME__", esc(themeName))
    .replaceAll("__DOMAIN__", esc(meta.domain || "N/A"))
    .replaceAll("__THEME_SAFE__", esc(theme))
    .replace("__CARDS__", entry.html);

  return new Response(html, {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "public, max-age=3600",
    },
  });
}
